#!/bin/sh
set -e
envsubst '$PUBLIC_REST_URL $PUBLIC_RPC_URL $PUBLIC_WEB3AUTH_CLIENT_ID $PUBLIC_WEB3AUTH_NETWORK $PUBLIC_MORPHEUS_URL $PUBLIC_MORPHEUS_MODEL $PUBLIC_MORPHEUS_API_KEY $PUBLIC_PWR_DENOM $PUBLIC_GAS_PRICE $PUBLIC_CHAIN_ID $PUBLIC_FAUCET_URL' \
  < /docker/config.js.template > /usr/share/nginx/html/config.js
exec "$@"
